[package]
authors = ['Joystream contributors']
build = 'build.rs'
edition = '2018'
name = 'chain-spec-builder'
version = '8.1.0'

[dependencies]
enum-utils = "0.1.2"
async-std = {version = "1.9.0", features = ["attributes"]}
futures-util = "0.3.15"
clap = { version = "3.1.18", features = ["derive"] }
rand = "0.8"
sc-keystore = { git = 'https://github.com/joystream/substrate.git', rev = 'd29a53b11c3e530d1656eef502cb0f1f8fff3522' }
sc-telemetry = { git = 'https://github.com/joystream/substrate.git', rev = 'd29a53b11c3e530d1656eef502cb0f1f8fff3522' }
sc-chain-spec = { git = 'https://github.com/joystream/substrate.git', rev = 'd29a53b11c3e530d1656eef502cb0f1f8fff3522' }
sp-core = { git = 'https://github.com/joystream/substrate.git', rev = 'd29a53b11c3e530d1656eef502cb0f1f8fff3522' }
sp-keystore = { git = 'https://github.com/joystream/substrate.git', rev = 'd29a53b11c3e530d1656eef502cb0f1f8fff3522' }
joystream-node = { path = "../../node" }
serde_json = "1.0.79"