metadata:
  source: wss://babylon-sub-1.joystream.app/staging/rpc
  blockHash: '0x206a6cca31333cb19ee120cde7455e13eea368ec3f6176d0cd48698228410489'
events:
  - members.MemberRegistered
  - members.MemberUpdatedAboutText
  - members.MemberUpdatedAvatar
  - members.MemberUpdatedHandle
  - members.MemberSetRootAccount
  - members.MemberSetControllerAccount
calls:
  - members.buyMembership
  - members.addScreenedMember
outDir: ./generated/types
customTypes:
  lib: '@joystream/types/augment/all/types'
  typedefsLoc: '../types/augment/all/defs.json'
