[package]
name = 'pallet-proposals-engine'
version = '6.0.0'
authors = ['Joystream contributors']
edition = '2018'

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = 'parity-scale-codec', version = '3.1.2', default-features = false, features = ['derive'] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
sp-std = { package = 'sp-std', default-features = false, git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0'}
frame-support = { package = 'frame-support', default-features = false, git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0'}
frame-system = { package = 'frame-system', default-features = false, git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0'}
pallet-timestamp = { package = 'pallet-timestamp', default-features = false, git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0'}
sp-arithmetic = { package = 'sp-arithmetic', default-features = false, git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0'}
sp-runtime = { package = 'sp-runtime', default-features = false, git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0'}
balances = { package = 'pallet-balances', default-features = false, git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0'}
common = { package = 'pallet-common', default-features = false, path = '../../common'}
staking-handler = { package = 'pallet-staking-handler', default-features = false, path = '../../staking-handler'}

# Benchmark dependencies.
frame-benchmarking = { package = 'frame-benchmarking', default-features = false, git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0', optional = true}
membership = { package = 'pallet-membership', default-features = false, path = '../../membership', optional = true}
council = { package = 'pallet-council', default-features = false, path = '../../council', optional = true}
referendum = { package = 'pallet-referendum', default-features = false, path = '../../referendum', optional = true}

[dev-dependencies]
sp-io = { package = 'sp-io', default-features = false, git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0'}
sp-core = { package = 'sp-core', default-features = false, git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0'}
council = { package = 'pallet-council', default-features = false, path = '../../council'}
membership = { package = 'pallet-membership', default-features = false, path = '../../membership'}
referendum = { package = 'pallet-referendum', default-features = false, path = '../../referendum'}

[features]
default = ['std']
runtime-benchmarks = [
    'frame-benchmarking/runtime-benchmarks',
    'membership/runtime-benchmarks',
    'council/runtime-benchmarks',
    'referendum/runtime-benchmarks',
	'common/runtime-benchmarks',
]
std = [
	'serde',
	'codec/std',
	'sp-std/std',
	'frame-support/std',
	'frame-system/std',
	'pallet-timestamp/std',
	'sp-arithmetic/std',
	'sp-runtime/std',
	'balances/std',
    'common/std',
    'staking-handler/std',
	'council/std',
	'referendum/std',
	'membership/std',
	'scale-info/std',
	'frame-benchmarking?/std'
]
try-runtime = [ "frame-support/try-runtime"]
