[package]
name = "node-inspect"
version = "0.9.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.2.2" }
thiserror = "1.0"
sc-cli = { package = 'sc-cli', git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0' }
sc-client-api = { package = 'sc-client-api', git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0' }
sc-executor = { package = 'sc-executor', git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0' }
sc-service = { package = 'sc-service', git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0', default-features = false }
sp-blockchain = { package = 'sp-blockchain', git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0' }
sp-core = { package = 'sp-core', git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0' }
sp-runtime = { package = 'sp-runtime', git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0' }
overrides = { package = "overrides", path = "../overrides" }
