[package]
authors = ['Joystream contributors']
edition = '2018'
name = 'session-keys'
version = '1.0.0'

[dependencies]
enum-utils = "0.1.2"
async-std = {version = "1.9.0", features = ["attributes"]}
futures-util = "0.3.15"
clap = { version = "3.1.18", features = ["derive"] }
rand = "0.8"
sc-keystore = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0' }
sc-telemetry = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0' }
sc-chain-spec = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0' }
sp-core = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0' }
sp-keystore = { git = 'https://github.com/paritytech/polkadot-sdk.git', tag = 'polkadot-v1.7.0' }
joystream-node = { path = "../../node" }
serde_json = "1.0.79"