name: node-network
runtime: nodejs
description: Kubernetes IaC for Joystream RPC and Validator nodes
template:
  config:
    aws:profile:
      default: joystream-user
    aws:region:
      default: us-east-1
    isMinikube:
      description: Whether you are deploying to minikube
      default: false
    numberOfValidators:
      description: Number of validators as starting nodes
      default: 2
    networkSuffix:
      description: Suffix to attach to the network id and name
      default: 8129
    isLoadBalancerReady:
      description: Whether the load balancer service is ready and has been assigned an IP
      default: false
    nodeImage:
      description: Docker image with tag to be used as validator and RPC nodes
      default: 'joystream/node:latest'
