[package]
name = 'substrate-proposals-codex-module'
version = '2.0.0'
authors = ['Joystream contributors']
edition = '2018'

[features]
default = ['std']
no_std = []
std = [
    'codec/std',
    'rstd/std',
    'srml-support/std',
    'primitives/std',
    'sr-primitives/std',
    'system/std',
    'timestamp/std',
    'serde',
    'proposal_engine/std',
    'proposal_discussion/std',
    'stake/std',
    'balances/std',
    'membership/std',
    'governance/std',
    'mint/std',
    'roles/std',
]


[dependencies.num_enum]
default_features = false
version = "0.4.2"

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.rstd]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-std'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.sr-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-primitives'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.srml-support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-support'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-system'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.timestamp]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-timestamp'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.balances]
package = 'srml-balances'
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-io'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.stake]
default_features = false
package = 'substrate-stake-module'
path = '../../stake'

[dependencies.membership]
default_features = false
package = 'substrate-membership-module'
path = '../../membership'

[dependencies.governance]
default_features = false
package = 'substrate-governance-module'
path = '../../governance'

[dependencies.mint]
default_features = false
package = 'substrate-token-mint-module'
path = '../../token-minting'

[dependencies.proposal_engine]
default_features = false
package = 'substrate-proposals-engine-module'
path = '../engine'

[dependencies.proposal_discussion]
default_features = false
package = 'substrate-proposals-discussion-module'
path = '../discussion'

[dependencies.common]
default_features = false
package = 'substrate-common-module'
path = '../../common'

[dependencies.content_working_group]
default_features = false
package = 'substrate-content-working-group-module'
path = '../../content-working-group'

[dependencies.roles]
default_features = false
package = 'substrate-roles-module'
path = '../../roles'

[dev-dependencies.hiring]
default_features = false
package = 'substrate-hiring-module'
path = '../../hiring'

[dev-dependencies.versioned_store]
default_features = false
package ='substrate-versioned-store'
path = '../../versioned-store'

[dependencies.versioned_store]
default_features = false
package ='substrate-versioned-store'
path = '../../versioned-store'

[dev-dependencies.versioned_store_permissions]
default_features = false
package = 'substrate-versioned-store-permissions-module'
path = '../../versioned-store-permissions'

[dev-dependencies.recurring_rewards]
default_features = false
package = 'substrate-recurring-reward-module'
path = '../../recurring-reward'
