[package]
name = 'pallet-proposals-codex'
version = '4.0.2'
authors = ['Joystream contributors']
edition = '2018'

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = 'parity-scale-codec', version = '2.1.1', default-features = false, features = ['derive'] }
sp-std = { package = 'sp-std', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'}
frame-support = { package = 'frame-support', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'}
sp-arithmetic = { package = 'sp-arithmetic', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'}
sp-runtime = { package = 'sp-runtime', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'}
frame-system = { package = 'frame-system', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'}
staking = { package = 'pallet-staking', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'}
pallet-timestamp = { package = 'pallet-timestamp', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'}
working-group = { package = 'pallet-working-group', default-features = false, path = '../../working-group'}
common = { package = 'pallet-common', default-features = false, path = '../../common'}
proposals-engine = { package = 'pallet-proposals-engine', default-features = false, path = '../engine'}
proposals-discussion = { package = 'pallet-proposals-discussion', default-features = false, path = '../discussion'}
constitution = { package = 'pallet-constitution', default-features = false, path = '../../constitution'}
membership = { package = 'pallet-membership', default-features = false, path = '../../membership'}
blog = { package = 'pallet-blog', default-features = false, path = '../../blog'}
balances = { package = 'pallet-balances', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353', optional = true}

# Benchmarking dependencies
frame-benchmarking = { package = 'frame-benchmarking', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353', optional = true}
council = { package = 'pallet-council', default-features = false, path = '../../council', optional = true}

[dev-dependencies]
sp-io = { package = 'sp-io', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'}
sp-core = { package = 'sp-core', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'}
sp-staking = { package = 'sp-staking', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'}
pallet-staking-reward-curve = { package = 'pallet-staking-reward-curve', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'}
strum = {version = "0.19", default-features = false}
staking-handler = { package = 'pallet-staking-handler', default-features = false, path = '../../staking-handler'}
referendum = { package = 'pallet-referendum', default-features = false, path = '../../referendum'}
council = { package = 'pallet-council', default-features = false, path = '../../council'}
balances = { package = 'pallet-balances', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'}

[features]
default = ['std']
runtime-benchmarks = ['frame-benchmarking', 'balances', 'council']
std = [
    'serde',
    'codec/std',
    'sp-std/std',
    'frame-support/std',
    'sp-arithmetic/std',
    'sp-runtime/std',
    'frame-system/std',
    'staking/std',
    'pallet-timestamp/std',
    'working-group/std',
    'common/std',
    'proposals-engine/std',
    'proposals-discussion/std',
    'constitution/std',
]
