[package]
name = 'pallet-proposals-codex'
version = '6.0.0'
authors = ['Joystream contributors']
edition = '2018'

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = 'parity-scale-codec', version = '3.1.2', default-features = false, features = [
    'derive',
] }
scale-info = { version = "2.1.1", default-features = false, features = [
    "derive",
] }
sp-std = { package = 'sp-std', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
sp-core = { package = 'sp-core', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
frame-support = { package = 'frame-support', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
sp-arithmetic = { package = 'sp-arithmetic', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
sp-runtime = { package = 'sp-runtime', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
frame-system = { package = 'frame-system', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
staking = { package = 'pallet-staking', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
pallet-timestamp = { package = 'pallet-timestamp', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
working-group = { package = 'pallet-working-group', default-features = false, path = '../../working-group' }
common = { package = 'pallet-common', default-features = false, path = '../../common' }
proposals-engine = { package = 'pallet-proposals-engine', default-features = false, path = '../engine' }
proposals-discussion = { package = 'pallet-proposals-discussion', default-features = false, path = '../discussion' }
constitution = { package = 'pallet-constitution', default-features = false, path = '../../constitution' }
membership = { package = 'pallet-membership', default-features = false, path = '../../membership' }
content = { package = 'pallet-content', default-features = false, path = '../../content' }
balances = { package = 'pallet-balances', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = 'd29a53b11c3e530d1656eef502cb0f1f8fff3522', optional = true }
token = { package = 'pallet-project-token', default-features = false, path = '../../project-token' }

# Benchmarking dependencies
frame-benchmarking = { package = 'frame-benchmarking', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e', optional = true }
council = { package = 'pallet-council', default-features = false, path = '../../council', optional = true }

[dev-dependencies]
sp-io = { package = 'sp-io', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
sp-core = { package = 'sp-core', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
sp-staking = { package = 'sp-staking', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
pallet-staking-reward-curve = { package = 'pallet-staking-reward-curve', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
strum = { version = "0.19", default-features = false }
staking-handler = { package = 'pallet-staking-handler', default-features = false, path = '../../staking-handler' }
referendum = { package = 'pallet-referendum', default-features = false, path = '../../referendum' }
council = { package = 'pallet-council', default-features = false, path = '../../council' }
balances = { package = 'pallet-balances', default-features = false, git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
frame-election-provider-support = { package = 'frame-election-provider-support', git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
pallet-bags-list = { package = 'pallet-bags-list', git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }
sp-npos-elections = { package = 'sp-npos-elections', git = 'https://github.com/joystream/substrate.git', rev = '50cf239147a6f569e563bcadec6c7a1c5ad5c67e' }

[features]
default = ['std']
runtime-benchmarks = [
    'frame-benchmarking/runtime-benchmarks',
    'balances/runtime-benchmarks',
    'council/runtime-benchmarks',
    'common/runtime-benchmarks',
]
std = [
    'serde',
    'codec/std',
    'sp-std/std',
    'sp-core/std',
    'frame-support/std',
    'sp-arithmetic/std',
    'sp-runtime/std',
    'frame-system/std',
    'pallet-timestamp/std',
    'working-group/std',
    'common/std',
    'proposals-engine/std',
    'proposals-discussion/std',
    'constitution/std',
    'council/std',
    'membership/std',
    'content/std',
    'token/std',
    'staking/std',
    'scale-info/std',
    'frame-election-provider-support/std',
    'sp-staking/std',
]
try-runtime = ["frame-support/try-runtime"]
