---
# Setup joystream code, build docker image

- name: Build joystream-node docker image and push to docker hub
  hosts: all

  tasks:
    - name: Install tools
      include_role:
        name: common
        tasks_from: install-tools

    - name: Get code from git repo
      include_role:
        name: common
        tasks_from: get-code-git

    - name: Log into DockerHub
      community.docker.docker_login:
        username: '{{ docker_username }}'
        password: '{{ docker_password }}'

    - name: Build an image and push it to a private repo
      community.docker.docker_image:
        build:
          path: '{{ remote_code_path }}'
          dockerfile: '{{ dockerfile }}'
          platform: '{{ platform }}'
          args:
            CARGO_FEATURES: '{{ cargo_features }}'
        name: '{{ repository }}'
        tag: '{{ tag_name }}'
        push: true
        source: build
      # Run in async fashion for max duration of 2 hours
      async: 7200
      poll: 0
      register: build_result

    - name: Check on build async task
      async_status:
        jid: '{{ build_result.ansible_job_id }}'
      register: job_result
      until: job_result.finished
      # Max number of times to check for status
      retries: 72
      # Check for the status every 100s
      delay: 100
