[package]
name = "joystream-node-runtime"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
integer-sqrt = { git = "https://github.com/paritytech/integer-sqrt-rs.git" }
safe-mix = { version = "1.0", default-features = false}
parity-codec-derive = { version = "^2.1" }
parity-codec = { version = "^2.2", default-features = false }
substrate-primitives = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
substrate-client = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
sr-std = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
sr-io = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
srml-support = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
srml-balances = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
srml-consensus = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
srml-executive = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
srml-aura = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
sr-primitives = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
srml-system = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
srml-indices = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
srml-timestamp = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
srml-sudo = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
sr-version = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
substrate-consensus-aura-primitives = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }

[features]
default = []
std = [
	"safe-mix/std",
	"parity-codec/std",
	"substrate-primitives/std",
	"substrate-client/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-balances/std",
	"srml-consensus/std",
	"srml-executive/std",
	"srml-aura/std",
	"sr-primitives/std",
	"srml-indices/std",
	"srml-system/std",
	"srml-timestamp/std",
	"srml-sudo/std",
	"sr-version/std",
]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []
