name: joystream-node
on:
  pull_request:
  push:

jobs:
  # test runtime benchmarks code correctness
  benchmarking:
    name: Benchmarking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: technote-space/get-diff-action@v3
        with:
          PREFIX_FILTER: |
            bin
            runtime
            runtime-modules
          SUFFIX_FILTER: |
            .rs
          FILES: |
            Cargo.lock
            Cargo.toml

      # TODO: Look for change in source code but no corresponding version bump of runtime or binaries
      # - name: Check version modified correctly
      #   if: env.GIT_DIFF

      - name: Toolchains
        run: |
          ./setup.sh
        if: env.GIT_DIFF

      - name: Build
        env:
          WASM_BUILD_TOOLCHAIN: nightly-2022-11-15
        run: |
          ./scripts/cargo-checks-with-benchmarking.sh &&
          ./scripts/cargo-build-with-benchmarking.sh
        if: env.GIT_DIFF

      - name: Test Generate Weights
        run: |
          ./scripts/generate-weights.sh 2 1 && git diff
        if: env.GIT_DIFF

  # Build and test joystream-node with all runtime profiles
  runtime_profiles:
    name: Runtime Profiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: technote-space/get-diff-action@v3
        with:
          PREFIX_FILTER: |
            bin
            runtime
            runtime-modules
          SUFFIX_FILTER: |
            .rs
          FILES: |
            Cargo.lock
            Cargo.toml
  
      - name: Toolchains
        run: |
          ./setup.sh
        if: env.GIT_DIFF
      - name: Production Runtime
        run: |
          yarn cargo-checks && yarn cargo-build
          ./target/release/call-sizes
        if: env.GIT_DIFF
      - name: OnRuntimeUpgrade (try-runtime)
        run: |
          cargo +nightly-2022-11-15 build --release --features try-runtime
          RUST_LOG=info,runtime=debug ./target/release/joystream-node try-runtime \
            --runtime ./target/release/wbuild/joystream-node-runtime/joystream_node_runtime.compact.compressed.wasm \
            on-runtime-upgrade \
            live \
            --uri wss://rpc.joystream.org:9944/
        if: env.GIT_DIFF
      - name: run_migrations test
        run: |
          RUN_MIGRATION_TESTS=true RUST_LOG=info cargo +nightly-2022-11-15 test remote_tests::run_migrations --release --features try-runtime
        if: env.GIT_DIFF
      - name: Staging Runtime
        env:
          RUNTIME_PROFILE: "STAGING"
        run: |
          yarn cargo-checks && yarn cargo-build
        if: env.GIT_DIFF
      - name: Playground Runtime
        env:
          RUNTIME_PROFILE: "PLAYGROUND"
        run: |
          yarn cargo-checks && yarn cargo-build
        if: env.GIT_DIFF
      - name: Testing Runtime
        env:
          RUNTIME_PROFILE: "TESTING"
        run: |
          yarn cargo-checks && yarn cargo-build
        if: env.GIT_DIFF
      - name: Fast Production Runtime
        env:
          RUNTIME_PROFILE: "FAST-PROD"
        run: |
          yarn cargo-checks && yarn cargo-build
        if: env.GIT_DIFF
